delete from TEMPORADA;
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2001-2002', '2001');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2002-2003', '2002');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2003-2004', '2003');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2004-2005', '2004');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2005-2006', '2005');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2006-2007', '2006');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2007-2008', '2007');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2008-2009', '2008');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2009-2010', '2009');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2010-2011', '2010');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2011-2012', '2011');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2012-2013', '2012');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2013-2014', '2013');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2014-2015', '2014');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2015-2016', '2015');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2016-2017', '2016');
INSERT INTO `TEMPORADA` (`TEMPORADA`, `ANHO`) VALUES ('2017-2018', '2017');

delete from POSICION;
INSERT INTO `POSICION` (`POSICION`) VALUES ('S/A');
INSERT INTO `POSICION` (`POSICION`) VALUES ('PORTERO');
INSERT INTO `POSICION` (`POSICION`) VALUES ('CIERRE');
INSERT INTO `POSICION` (`POSICION`) VALUES ('ALA-CIERE');
INSERT INTO `POSICION` (`POSICION`) VALUES ('ALA');
INSERT INTO `POSICION` (`POSICION`) VALUES ('ALA-PIVOT');
INSERT INTO `POSICION` (`POSICION`) VALUES ('PIVOT');
INSERT INTO `POSICION` (`POSICION`) VALUES ('ENTRENADOR');

delete from COMPETICION;
INSERT INTO `COMPETICION` (`COMPETICION`) VALUES ('PRIMERA DIVISION');

delete from FASE_COMPETICION;
INSERT INTO `FASE_COMPETICION` (`FASE_COMPETICION`) VALUES ('LIGA REGULAR');

DELETE FROM PLANTILLA;
DELETE FROM EQUIPO;
DELETE FROM JUGADOR;